### ISSUE TITLE
How to compile tf2.1

### ISSUE THREAD

**Issue by wangwenchao-job** [sitting-duck/stuff#14]
Hello, may I ask how to compile tf2.1, the following is my configuration

tf2.1
windows 10
bazel 0.29
cuda 10.1
cudnn 7.6.5

**Comment by wangwenchao-job** [comment]
> Hello, may I ask how to compile tf2.1, the following is my configuration
> 
> tf2.1
> windows 10
> bazel 0.29
> cuda 10.1
> cudnn 7.6.5

![image](https://user-images.githubusercontent.com/57739867/79994066-1488a500-84e8-11ea-855b-3892c891267b.png)

this is the code：
https://github.com/tensorflow/tensorflow/blob/v2.2.0-rc2/tensorflow/examples/multibox_detector/main.cc

**Comment by sitting-duck** [comment]
Unfortunately I do not have a guide for Tensorflow 2 because I have not tried yet with TF2. I will go ahead and close this issue, but I hope to do a tutorial for TF2 in the future.
