### ISSUE TITLE
Building the .dll and .lib files

### ISSUE THREAD

**Issue by Patrikvs94** [sitting-duck/stuff#16]
Hey there! I'm trying to build Tensorflow and I'm on step 10 & 11. Is it normal to get a lot of warnings during building in step 10? And my building of the .lib file took 7 seconds in total, is this normal?

**Comment by Patrikvs94** [comment]
Also, I tried to compile the code you posted at the beginning of Step 14, but I got around 498 errors telling me that I'm missing header files. Example is graph.ph.h is missing and it's supposed to be generated by bazel, but it isn't for some reason.

**Comment by sitting-duck** [comment]
Hmmmm... very interesting.

I use the search bar on Github all the time to find exactly where the
header is, and then I check that I have that on my hard drive,
If the search bar can't find it, then yeah, I'd guess it's a generated
header file,

Are you compiling tf 1.14 or some other version?
I have noticed that the version of bazel with the version of Tensorflow
does matter.

If I can't help you well over email, would you like to do a TeamViewer
session or something?
Feel free to ping ashley.tharp@gmail.com on Google Hangouts. I'm at work at
the moment, but I'll try to get back to you as soon as possible.

**Comment by sitting-duck** [comment]
No response from user after over 6 months, cannot recreate issue without any more information, will go ahead and close this issue.
