### ISSUE TITLE
After successfull build process how shall I install the generated files for deployment

### ISSUE THREAD

**Issue by OronG13** [sitting-duck/stuff#17]
Hello,
Thanks to your guidance I successfully build the tesnorflow.lib.
My setup is:

- TF 2.3
- Win10
- Visual studio 2019
- CUDA 11.0
- CuDNN 8

Now I want to arrange all generated material in order to package it correctly.
My purpose is to create a directory which will include all required files for application usage.

The following directories  were generated:

- bazel-bin
- bazel-out
- bazel-tensorflow-2.3.0
- bazel-testlogs

The tensorflow.lib file exist in \bazel-bin\tensorflow\.

How can I create a kind of Install directory which will include this lib and its dependencies and all required header files which now are spread in all these mentioned directories?

Thanks,

**Comment by sitting-duck** [comment]
Ah, okay, I see what you mean,

I typically do something like this

bin - exe and dll go in here,
include - header files, cpp files maybe
lib - .lib file go in here

I may have two more top level dirs for x64 and x86 if I am doing multiple
platform builds.
Please let me know if you have any other questions, I am happy to help, and
so sorry for any delay getting back to you.

Do you mind if I publish this question and answer on my blog on medium.com?
I would credit you if you want, and send you the link for review,
https://ashley-tharp.medium.com/

**Comment by OronG13** [comment]
Hello Ashley,
Thank you for your response.

Of course you can share my question on your blog 👍 

Regarding your answer:
I just wanted to know if based on your experience I could quickly arrange the generated material.
I can always do the hard work which means take file by file\dir by dir till my application will successfully built.

I can share you my generated directories (~42GB) (described above).
It isn't make sense that all of this is required for application build process...

Of course there are obvious files and directories that shall be taken but in addition there are a lot of materiel that it isn't explicitly clear if it shall be taken or not.

Maybe I can take the directories structure of the Python tensorflow_core package which installed via pip command?
It resides under the following path:
..\site-packages\tensorflow_core\include
\site-packages\tensorflow_core\python\_pywrap_tensorflow_internal.lib

Thanks,

**Comment by sitting-duck** [comment]
Ah, I see,
I wish I had a script for this too,
I just searched for tensorflow.lib and tensorflow.dll and that was it for
me,

I did notice a huge number of extra .lib files and I still don't know what
they are for actually.

I'll let you know if I come up with anything.
