### ISSUE TITLE
missed too many headers

### ISSUE THREAD

**Issue by stereomatchingkiss** [sitting-duck/stuff#4]
After compile, I find out I missed so many headers and there is no instructions to tell us how should we include those files, where to find them etc. I download the source codes as you mentioned, include them, but there are more and more files cannot be found, building c++ api on tensorflow is totally a mess, after so many years it is still hard to use as hell

**Comment by sitting-duck** [comment]
Can you reach out to my gmail? (ashley.tharp@gmail.com) I may be able to compare my project with yours and see what the difference is. 

I can update my README once we discover what the issue was.

**Comment by sitting-duck** [comment]
Hey there, just checking in on this, are you still having this issue? I am here and I can help :)

**Comment by sitting-duck** [comment]
Hey there, did you ever manage to fix your issue with the missing headers? 
I would like to close this issue, but if there is any new info, I'd like to include it :)

**Comment by stereomatchingkiss** [comment]
Nope, thanks for your helps. I use another solution rather than tensorflow,
this is a library I would like to avoid to use it, really bad api design
compare with pytorch +  it is totally a mess to compile them to c++ libs,

Ashley <notifications@github.com> 於 2020年11月19日 週四 下午10:06寫道：

**Comment by sitting-duck** [comment]
Roger that. Thanks.
